**1. Створення масивів**

Створіть (кожен пункт оцінюється в 0.5 бала):
- Масив зі списку `[5, 15, 25, 35, 45]`
- Масив з нулів розміром 7
- Масив з одиниць розміром 6
- Масив з числами від 10 до 19 використовуючи `np.arange()`

In [1]:
# Імпорт бібліотеки numpy під скороченим псевдонімом np
import numpy as np

# Створення масиву із заданого списку
list = [5, 15, 25, 35, 45]
arr_from_list = np.array(list)
print(arr_from_list)

[ 5 15 25 35 45]


In [2]:
# Створення масиву з нулів розміром 7
zeros = np.zeros(7,)
print(zeros)

[0. 0. 0. 0. 0. 0. 0.]


In [3]:
# Створення масиву з одиниць розміром 6
ones = np.ones(6,)
print(ones)

[1. 1. 1. 1. 1. 1.]


In [5]:
# Створення масиву з числами від 10 до 19
arr = np.arange(10, 20)
print(arr)

[10 11 12 13 14 15 16 17 18 19]



---

**2. Базові операції**

Створіть Numpy-масив зі значеннями [12, 24, 36, 48, 60].

Виконайте наступні операції над **оригінальним** масивом і запишіть у нову змінну результат (кожен пункт оцінюється в 0.5 бала):
- Помножте всі елементи на 2
- Додайте до всіх елементів 10
- Піднесіть всі елементи до квадрату
- Обчисліть квадратний корінь з усіх елементів

Виведіть результат виконання кожної операції.

In [8]:
# Створення заданого масиву
arr = np.array([12, 24, 36, 48, 60])
print(f"Початковий масив: {arr}")

# Домноження всіх елементів масиву на 2
x2_arr = arr * 2
print(f"Масив, домножений на 2: {x2_arr}")

# Збільшення всіх елементів масиву на 10
arr_add_10 = arr + 10
print(f"Масив з елементами, збільшеними на 10: {arr_add_10}")

# Піднесення всіх елементів масиву до квадрату
xx2_arr = arr ** 2
print(f"Масив, піднесений до квадрату: {xx2_arr}")

# Обчислення квадратного кореня з усіх елементів масиву
sqrt_arr = np.sqrt(arr)
print(f"Масив після здобуття квадратного кореня з елементів: {sqrt_arr}")

Початковий масив: [12 24 36 48 60]
Масив, домножений на 2: [ 24  48  72  96 120]
Масив з елементами, збільшеними на 10: [22 34 46 58 70]
Масив, піднесений до квадрату: [ 144  576 1296 2304 3600]
Масив після здобуття квадратного кореня з елементів: [3.46410162 4.89897949 6.         6.92820323 7.74596669]



---

**3. Статистичні функції**

Створіть Numpy-масив `data` зі значеннями [18, 27, 33, 41, 52, 68, 79].

Обчисліть використовуючи функціонал numpy (кожен пункт оцінюється в 0.5 бала):
- Середнє значення
- Мінімум
- Максимум
- Суму всіх елементів

In [9]:
# Створення заданого масиву
data = np.array([18, 27, 33, 41, 52, 68, 79])
print(f"Масив: {data}")

# Обчислення середнього значення масиву
mean_data = np.mean(data)
print(f"Середнє значення масиву: {mean_data}")

# Обчислення мінімуму масиву
min_data = np.min(data)
print(f"Мінімум масиву: {min_data}")

# Обчислення максимуму масиву
max_data = np.max(data)
print(f"Максимум масиву: {max_data}")

# Обчислення суми всіх елементів масиву
sum_data = np.sum(data)
print(f"Сума всіх елементів масиву: {sum_data}")

Масив: [18 27 33 41 52 68 79]
Середнє значення масиву: 45.42857142857143
Мінімум масиву: 18
Максимум масиву: 79
Сума всіх елементів масиву: 318



---

**4. Індексація**

Створіть Numpy-масив `arr` зі значеннями [15, 22, 35, 44, 58, 67].

Виведіть (кожен пункт оцінюється в 0.5 бала):
- Перший елемент
- Останній елемент
- Елементи з індексами 1 до 3
- Елементи більші за 40

In [13]:
# Створення заданого масиву
arr = np.array([15, 22, 35, 44, 58, 67])
print(f"Масив: {arr}")

# Виведення першого елемента масиву
print(f"Перший елемент масиву: {arr[0]}")

# Виведення останнього елемента масиву
print(f"Останній елемент масиву: {arr[-1]}")

# Виведення елементів масиву з індексами від 1 до 3
print(f"Елементи масиву з індексами від 1 до 3: {arr[1:4]}")

# Виведення елементів масиву, більших за 40
mask = arr > 40
print(f"Елементи масиву, більші за 40: {arr[mask]}")

Масив: [15 22 35 44 58 67]
Перший елемент масиву: 15
Останній елемент масиву: 67
Елементи масиву з індексами від 1 до 3: [22 35 44]
Елементи масиву, більші за 40: [44 58 67]



---


**5. Двовимірні масиви**

Задано матрицю 3x3.

Виконайте наступні дії з функціоналом Numpy (кожен пункт оцінюється в 0.5 бала):
- Виведіть форму (shape) матриці
- Виведіть перший рядок
- Виведіть другу колонку
- Обчисліть суму всіх елементів
- Обчисліть середнє всіх елементів

In [15]:
matrix = np.array([[2, 4, 6],
                   [8, 10, 12],
                   [14, 16, 18]])

In [27]:
# Виведення форми матриці
print(f"Форма матриці: {np.shape(matrix)}")

# Виведення першого рядка матриці
print(f"Перший рядок матриці: {matrix[0, :]}")

# Виведення другої колонки матриці
print(f"Друга колонка матриці: {matrix[:, 1]}")

# Обчислення суми всіх елементів матриці
print(f"Сума всіх елементів матриці: {np.sum(matrix)}")

# Обчислення середнього значення всіх елементів матриці
print(f"Середнє значення всіх елементів матриці: {np.mean(matrix)}")

Форма матриці: (3, 3)
Перший рядок матриці: [2 4 6]
Друга колонка матриці: [ 4 10 16]
Сума всіх елементів матриці: 90
Середнє значення всіх елементів матриці: 10.0
