### Завдання 1: Створення матриць та векторів
1. Створіть `numpy` вектор `vector` розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1. Можна скористатись двома альтернативними варіантами:
  1. Генерація випадкових чисел з модулем [`random.uniform`](https://docs.python.org/3/library/random.html).
  2. Створення вектора з допомогою метода `numpy` [np.random.rand](https://numpy.org/doc/stable/reference/random/generated/numpy.random.rand.html)

2. Створіть матрицю `matrix` типу `numpy.array` розмірності 3x3 з наступними значеннями

  $$
  matrix = \begin{bmatrix}
  11 & 14 & 17 \\
  20 & 23 & 26 \\
  29 & 32 & 35
  \end{bmatrix}
  $$

  будь-яким відомими Вам способом.

Виведіть на екран вектор і матрицю, а також їх розміри.


In [1]:
# 1. Створення numpy вектора vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1 двома способами

# Імпортування необхідних бібліотек
import numpy as np

# 1.1. Створення numpy вектора vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1 способом генерації випадкових чисел
# з модулем random.uniform
vector = np.random.uniform(0, 1, 10)

# Виведення створеного вектора vector
print(f"vector = {vector}")

# Виведення розмірів вектора vector
print(f"Розміри вектора vector: {vector.shape}")

vector = [0.31607243 0.09790634 0.40277614 0.26971906 0.8537679  0.72742655
 0.16926968 0.9375237  0.58306569 0.52175506]
Розміри вектора vector: (10,)


In [2]:
# 1.2. Створення numpy вектора vector розмірністю 10 з випадковими дійсними значеннями в діапазоні від 0 до 1 з допомогою 
# метода numpy np.random.rand
vector = np.random.rand(10)

# Виведення створеного вектора vector
print(f"vector = {vector}")

# Виведення розмірів вектора vector
print(f"Розміри вектора vector: {vector.shape}")

vector = [0.47912327 0.95410166 0.58929369 0.39682058 0.47282995 0.44330745
 0.54119268 0.37026132 0.36060083 0.67704951]
Розміри вектора vector: (10,)


In [3]:
# 2. Створення заданої матриці matrix типу numpy.array розмірності 3x3
matrix = np.array([[11, 14, 17],
                   [20, 23, 26],
                   [29, 32, 35]])

# Виведення створеної матриці matrix
print("Матриця matrix:")
print(matrix)

# Виведення розмірів матриці matrix
print(f"Розміри матриці matrix: {matrix.shape}")

Матриця matrix:
[[11 14 17]
 [20 23 26]
 [29 32 35]]
Розміри матриці matrix: (3, 3)



### Завдання 2: Операції над векторами та матрицями
Виконайте кожну з зазначених операцій над зазначеними оʼєктами і виведіть результат на екран:
1. Додайте до кожного значення вектора `vector` число 10 і округліть кожне значення до 2 знаків після коми без використання циклів.
2. Помножте кожен елемент матриці з першого завдання на 2 без використання циклів.
3. Створіть новий вектор, який містить квадрат кожного значення `vector`, без циклів.


In [16]:
# 2.1. Додавання до кожного значення вектора vector число 10 й округлення кожного значення до 2 знаків після коми без використання циклів
vector_plus10_round = np.round(vector + 10, 2)

# Виведення результату
print(f"Вектор vector після збільшення кожного значення на 10 й округлення до 2 знаків після коми:")
print(vector_plus10_round)

Вектор vector після збільшення кожного значення на 10 й округлення до 2 знаків після коми:
[10.48 10.95 10.59 10.4  10.47 10.44 10.54 10.37 10.36 10.68]


In [5]:
# 2.2. Множення кожного елемента матриці matrix з першого завдання на 2 без використання циклів
matrix_x2 = 2 * matrix

# Виведення результату
print(f"Матриця matrix після множення кожного значення на 2:")
print(matrix_x2)

Матриця matrix після множення кожного значення на 2:
[[22 28 34]
 [40 46 52]
 [58 64 70]]


In [17]:
# 2.3. Створення нового вектора квадратів кожного значення vector без циклів
vector_xx2 = vector ** 2

# Виведення результату
print(f"Вектор vector після піднесення кожного значення до квадрату: {vector_xx2}")

Вектор vector після піднесення кожного значення до квадрату: [0.22955911 0.91030998 0.34726706 0.15746658 0.22356816 0.1965215
 0.29288952 0.13709345 0.13003296 0.45839603]



### Завдання 3: Множення матриць
1. Задані дві матриці `A` і `B`розмірностями 3x2 та 2х3. Виконайте їхнє множення, щоб отримати матрицю 2x2. Виведіть результуючу матрицю `result_matrix` на екран.

2. Заданий вектор `C` розмірністю 2х1. Подумайте спочатку, яку розмірність Ви отримаєте, коли домножите `result_matrix` на вектор `C` і який результат буде. А потім виконайте множення і виведіть результат на екран.

3. Задана матриця `D` розмірністю 2х2. Подумайте спочатку, яку розмірність Ви отримаєте, коли домножите `result_matrix` на матрицю `D` і який результат буде. А потім виконайте множення і виведіть результат на екран.

In [7]:
A = np.array(
    [[0.18, 0.53],
     [0.75, 0.47],
     [0.35, 0.21]])

B = np.array(
    [[0.17, 0.58, 0.75],
     [0.38, 0.11, 0.15]])

C = np.array([[0], [1]])

D = np.array([[0, 1], [1, 0]])

display(A, B, C, D)

array([[0.18, 0.53],
       [0.75, 0.47],
       [0.35, 0.21]])

array([[0.17, 0.58, 0.75],
       [0.38, 0.11, 0.15]])

array([[0],
       [1]])

array([[0, 1],
       [1, 0]])

In [8]:
# 3.1. Множення матриць A і B, щоб отримати результуючу матрицю result_matrix розмірності 2x2
result_matrix = np.dot(B, A)

# Виведення результату
print(f"Результуюча матриця result_matrix:")
print(result_matrix)

Результуюча матриця result_matrix:
[[0.7281 0.5202]
 [0.2034 0.2846]]


In [13]:
# 3.2. Множення матриці result_matrix на вектор C
result_matrix_x_C = np.dot(result_matrix, C)

# Виведення результату
print(f"Результат множення матриці result_matrix на вектор C:")
print(result_matrix_x_C)

Результат множення матриці result_matrix на вектор C:
[[0.5202]
 [0.2846]]


In [14]:
# 3.3. Множення матриці result_matrix на матрицю D
result_matrix_x_D = np.dot(result_matrix, D)

# Виведення результату
print(f"Результат множення матриці result_matrix на матрицю D:")
print(result_matrix_x_D)

Результат множення матриці result_matrix на матрицю D:
[[0.5202 0.7281]
 [0.2846 0.2034]]



### Завдання 4: Транспонування матриць
1. Транспонуйте `result_matrix`.
2. Зробіть транспонування вектора `vector` і виведіть форму нової структури. Чи бачите ви зміну?
3. Використайте операцію `numpy.expand_dims` над вектором `vector` з аргументом axis=1. Запишіть отриманий результат в змінну `column_vector` і виведіть на екран. Порівняйте з `vector`.
4. Зробіть транспонування `column_vector`, виведіть результат на екран разом з розмірностями отриманої структури.




In [9]:
# 4.1. Транспонування result_matrix
result_matrix_T = result_matrix.T

# Виведення результату
print(f"Транспонована матриця result_matrix:")
print(result_matrix.T)

Транспонована матриця result_matrix:
[[0.7281 0.2034]
 [0.5202 0.2846]]


In [10]:
# 4.2. Транспонування вектора vector
vector_T = vector.T

# Виведення результату
print(f"Транспонований вектор vector: {vector_T}")

# Виведення форми транспонованого вектора vector
print(f"Розміри транспонованого вектора vector: {vector_T.shape}")

# Чи бачите ви зміну?
print("Ні, форма вектора vector після транспонування не змінилася.")

Транспонований вектор vector: [0.47912327 0.95410166 0.58929369 0.39682058 0.47282995 0.44330745
 0.54119268 0.37026132 0.36060083 0.67704951]
Розміри транспонованого вектора vector: (10,)
Ні, форма вектора vector після транспонування не змінилася.


In [11]:
# 4.3. Зміна форми вектора vector
column_vector = np.expand_dims(vector, axis = 1)

# Виведення результату
print(f"Вектор-стовпець vector:")
print(column_vector)

# Виведення форми вектора-стовпця vector
print(f"Розміри вектора-стовпця vector: {column_vector.shape}")

# Порівняння результату з vector
print("Форма вектора vector змінилася з рядка на стовпець, і тепер він має 2 виміри - 10 рядків та 1 стовпець.")

Вектор-стовпець vector:
[[0.47912327]
 [0.95410166]
 [0.58929369]
 [0.39682058]
 [0.47282995]
 [0.44330745]
 [0.54119268]
 [0.37026132]
 [0.36060083]
 [0.67704951]]
Розміри вектора-стовпця vector: (10, 1)
Форма вектора vector змінилася з рядка на стовпець, і тепер він має 2 виміри - 10 рядків та 1 стовпець.


In [12]:
# 4.4. Транспонування вектора column_vector
column_vector_T = column_vector.T

# Виведення результату
print(f"Транспонований вектор-стовпець vector: {column_vector_T}")

# Виведення форми транспонованого вектора vector
print(f"Розміри транспонованого вектора-стовпця vector: {column_vector_T.shape}")

Транспонований вектор-стовпець vector: [[0.47912327 0.95410166 0.58929369 0.39682058 0.47282995 0.44330745
  0.54119268 0.37026132 0.36060083 0.67704951]]
Розміри транспонованого вектора-стовпця vector: (1, 10)
